### ISSUE TITLE
Add start to test suite

### ISSUE THREAD

**Issue by JakeRoggenbuck** [jabacat/jml#8]

**Comment by JakeRoggenbuck** [comment]
Would this be useful?

**Comment by adamhutchings** [comment]
From how machine learning does things in that it slowly trains itself to become better rather than hitting on a definite solution, I think it might be better to have a demonstration suite instead. Ex: recognizing handwritten digits (MNIST), recognizing faces, predicting the next character of written input, etc. What do you think?

**Comment by JakeRoggenbuck** [comment]
A demonstration suite would be great to have. Would it replace a test suite? I was thinking of having unit tests for all of the math implementation because those can be hard to get right.

**Comment by adamhutchings** [comment]
That’s very true and I didn’t even think of that. Test suite sounds great then.

**Comment by thondascully** [comment]
Test suite + demonstrate suite for monitoring purposes are all great ideas

**Comment by adamhutchings** [comment]
@JakeRoggenbuck Once PR #9 is merged, tests for matrix and vector math would be very useful.

**Comment by adamhutchings** [comment]
@Sophon96, given that you are working on the build process may I secondarily assign you to this issue? A test suite would need some special build scripts or something similar.

**Comment by Sophon96** [comment]
Sure, no problem. I'll admit that I don't have experience with test suites
in C/C++ but I'll see what I can cook up!

**Comment by Sophon96** [comment]
Although Jake's already self-assigned so I don't want to compete lol

**Comment by adamhutchings** [comment]
Can work on this start yet or are we waiting for something more?

**Comment by Sophon96** [comment]
> Can work on this start yet or are we waiting for something more?

Already started, right after #14 was merged :)

**Comment by adamhutchings** [comment]
Yay

**Comment by JakeRoggenbuck** [comment]
https://gamesfromwithin.com/exploring-the-c-unit-testing-framework-jungle

**Comment by Sophon96** [comment]
> December 28, 2004\

I think it's outdated

> https://gamesfromwithin.com/exploring-the-c-unit-testing-framework-jungle

**Comment by JakeRoggenbuck** [comment]
haha yea that's fair. I'll try to find some more recent reviews of more recent frameworks

**Comment by Sophon96** [comment]
I've started with Catch2, which seems to be pretty popular and works pretty well so far.

**Comment by Sophon96** [comment]
Currently working on fixing #38, because I can't link my tests to actually run them yet LOL

**Comment by Sophon96** [comment]
I can push my untested test code tonight to #23 if anyone wants to try running it on a non-Windows machine.

**Comment by adamhutchings** [comment]
I'll give it a go when you have a chance.
